<% db_type = ENV["SUPPORT_API_DB_TYPE"].nil? ? "mysql" : ENV["SUPPORT_API_DB_TYPE"] %>

mysql_default: &mysql_default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: support_contacts
  password: support_contacts

postgresql_default: &postgresql_default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  # Necessary to allow creating a db with different encodings.
  # See http://www.postgresql.org/docs/9.1/static/manage-ag-templatedbs.html for details
  template: template0

development:
  <<: *<%= db_type%>_default
  database: support_contacts_development

test:
  <<: *<%= db_type%>_default
  database: support_contacts_test
